-- 添加軟刪除（垃圾筒）欄位到主要資料表
-- trashed_at 記錄放入垃圾筒的時間，NULL 表示正常資料
-- 垃圾筒中的資料保留 7 天，之後不再顯示

-- 訂單相關
ALTER TABLE orders ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE order_labels ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 報價單/服務單相關
ALTER TABLE service_orders ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_order_items ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_order_labels ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 採購單相關
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE purchase_order_items ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE purchase_order_labels ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 客戶相關
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 產品相關
ALTER TABLE products ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_types ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 供應商
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 用戶（員工）
ALTER TABLE users ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 倉庫
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 設置相關
ALTER TABLE companies ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE levels ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE currencies ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE phone_country_codes ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE shipping_methods ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE member_levels ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 優惠券
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE coupon_conditions ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 店舖和門店
ALTER TABLE stores ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 會計相關
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 項目相關
ALTER TABLE projects ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE project_tasks ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 人力資源
ALTER TABLE roles ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 訊息
ALTER TABLE messages ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 頁面和區塊
ALTER TABLE pages ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
-- blocks 已經有 deleted_at，不需要額外欄位

-- 部落格
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 車輛
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 出貨單
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 預約
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 稅務
ALTER TABLE product_taxes ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_taxes ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 物流公司
ALTER TABLE logistics_companies ADD COLUMN IF NOT EXISTS trashed_at TIMESTAMP WITH TIME ZONE;

-- 創建索引以加速查詢
CREATE INDEX IF NOT EXISTS idx_orders_trashed_at ON orders(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_service_orders_trashed_at ON service_orders(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_orders_trashed_at ON purchase_orders(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_customers_trashed_at ON customers(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_products_trashed_at ON products(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_services_trashed_at ON services(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_suppliers_trashed_at ON suppliers(trashed_at) WHERE trashed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_trashed_at ON users(trashed_at) WHERE trashed_at IS NOT NULL;
